dist: trusty
sudo: required
language: java
jdk: openjdk11

before_install: 
  - chmod +x server/mvnw
  
before_script:
  - psql -c 'create database ktsdb;' -U postgres

services:
  - postgresql

addons:
  sonarcloud:
    organization: ktsnvt-2020-t6
    token: 5505c51e689b73abc7924b1a44fa947266e29338

install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH" 
  
script:
  - cd server 
  - ./mvnw clean install -q
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=KTSNVT-2020-T6 
  

