dist: trusty
sudo: required
language: java
jdk: openjdk8
before_install: 
  - chmod +x server/mvnw
script: 
  - cd server 
  - ./mvnw clean install
  - ./mvnw sonar:sonar \
    - Dsonar.projectKey=ktsnvt \
    - Dsonar.host.url=http://localhost:9000 \
    - Dsonar.login=34fd8c2e0a77f0a62a68a3ffcf2c581d5f27f52f

services:
- postgresql


