dist: trusty
sudo: required
language: java
jdk: openjdk8


before_install: 
  - chmod +x server/mvnw
  
before_script:
  - psql -c 'create database ktsdb;' -U postgres

services:
  - postgresql

script: 
  - cd server 
  - ./mvnw clean install

  





