dist: trusty
sudo: required
language: java
jdk: openjdk8

before_script:
  - psql -c 'create database ktsdb;' -U postgres

services:
  - postgresql
  
before_install: 
  - chmod +x server/mvnw

  
script: 
  - cd server 
  - ./mvnw clean install 
  - ./mvnw sonar:sonar
  - ./mvnw clean verify-P sonar \
  - Dsonar.projectKey=ktsnvt \
  - Dsonar.host.url=http://localhost:9000 \
  - Dsonar.login=fd3dbcdcd9935ba02c48eee16d9b2e4bc864d7c4




