dist: trusty
sudo: required
language: java
jdk: openjdk11

before_install: 
  - chmod +x server/mvnw
  
before_script:
  - psql -c 'create database ktsdb;' -U postgres

services:
  - postgresql

addons:
  sonarcloud:
    organization: ktsnvt-2020-t6
    token: 5505c51e689b73abc7924b1a44fa947266e29338

script: 
  - cd server 
  - ./mvnw clean install
  - ./mvnw sonar:sonar -Dsonar.projectKey=KTSNVT-2020-T6 -Dsonar.organization=KTSNVT-2020-T6 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=5505c51e689b73abc7924b1a44fa947266e29338
  





